version: "2"
services:
  nginx:
    image: nginx
    links:
      - app
    volumes:
      - ./nginx/nginx.conf:/nginx.conf
    ports:
      - "8001:80"
    command: [nginx, -c, /nginx.conf]

  app:
    image: hrasoa/node
    working_dir: /var/www
    user: devel
    environment:
      - NODE_ENV: production
    expose:
      - "3000"
    volumes:
      - ./:/var/www
    command: [npm, start]