version: "2"

options:  
  verbose: true

syncs:
  #IMPORTANT: ensure this name is unique and does not match your other application container name
  pwa-sync: #tip: add -sync and you keep consistent names as a convention
    src: '../'
    sync_strategy: unison
    sync_userid: '1000'
    sync_excludes: [ '.git', '.DS_STORE', '.idea' ]
